stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t sample-microservice:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy:
  stage: deploy
  image: bitnami/oc:latest
  script:
    - oc config set-cluster k8s --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - oc config set-credentials admin --token="$KUBE_TOKEN"
    - oc config set-context default --cluster=k8s --user=admin
    - oc config use-context default
    - oc apply -f deployment.yaml